In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [2]:
# Write your code here
array = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
sigm = lambda x: 1/(1+np.exp(-x))
array2 = sigm(array[-5:])
print(array2)


[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [18]:
# Write your code here
x= np.array([3,1,4,2,6,1,4,8])
y= np.array([5,2,3,12,2,4,17,11])

print("a " +str(np.sum(x*y)))
print("b " + str(np.dot(x, y)))

print("c " + str(np.matmul(x, y)))



a 225
b 225
c 225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [37]:
# Write your code here
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2])
theta = np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])

fun = lambda x,y: -x*y
power = np.sum(fun(x[:],theta[:len(theta)-1]))
y = 1/(1+np.exp(power - theta[len(theta)-1]))
print(y)

0.2417699832615572


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [7]:
# Write your code here
A = np.array([1,2,1,3,0,1]).reshape(2,3)
print(A)
B = np.array([0.2,0.3]).reshape(2,1)
print(B)
print()
x = np.array([1,2,3])
result = (np.matmul(A,x)+B)
print(result)


[[1 2 1]
 [3 0 1]]
[[0.2]
 [0.3]]

[[8.2 6.2]
 [8.3 6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [12]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [24]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)
steam_df.tail(10)

user-id                  game-title behavior-name  value  zero
199990  128470551                Fallen Earth      purchase    1.0     0
199991  128470551                Fallen Earth          play    2.4     0
199992  128470551                 Magic Duels      purchase    1.0     0
199993  128470551                 Magic Duels          play    2.2     0
199994  128470551                 Titan Souls      purchase    1.0     0
199995  128470551                 Titan Souls          play    1.5     0
199996  128470551  Grand Theft Auto Vice City      purchase    1.0     0
199997  128470551  Grand Theft Auto Vice City          play    1.5     0
199998  128470551                        RUSH      purchase    1.0     0
199999  128470551                        RUSH          play    1.4     0

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [9]:
# Write your code here
steam_g = steam_df.loc[steam_df['behavior-name'] == 'purchase']
print(len(pd.unique(steam_g['user-id'])))

12393


**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [10]:
# Write your code here
steam_g = steam_df.loc[steam_df['game-title'] == 'The Elder Scrolls V Skyrim']
x = pd.unique(steam_g['user-id'])
print(len(x))

717


**Task 7.** How many purchases people made on average?

In [26]:
# Write your code here
users = len(pd.unique(steam_df['user-id']))
cond2 = steam_df['behavior-name'] == 'purchase'
g = steam_df[cond2]
group = g.groupby('user-id').sum()

print(group['value'].mean())



10.45033486645687


**Task 8.** Who bought the most games?

In [28]:
# Write your code here
cond2 = steam_df['behavior-name'] == 'purchase'
g = steam_df[cond2].groupby('user-id').sum()
g = g.sort_values(by='value', ascending=False).reset_index()
g = g.loc[:, ['user-id','value']]
display(g.head(1))

user-id   value
0  62990992  1075.0

**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [45]:
# Write your code here
cond = steam_df['behavior-name'] == 'play'
cond2 = steam_df['game-title'] == 'The Elder Scrolls V Skyrim'

g = steam_df

g = g.loc[cond & cond2]

g = g.sort_values(by='value', ascending=False).reset_index()


display(g['value'].mean())

104.71093057607091

**Task 10.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [52]:
# Write your code here
cond = steam_df['behavior-name'] == 'play'
g = steam_df[cond]
g = g.loc[:, ['game-title', 'value']]
g = g.groupby('game-title').sum()

g = g.sort_values(by='value', ascending=False).reset_index()


g.head(10)

game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7

**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [63]:
# Write your code here
cond = steam_df['behavior-name'] == 'play'
g = steam_df[cond]
g = g.loc[:, ['game-title', 'value']]
g = g.groupby('game-title')
g = g.mean()
g = g.sort_values(by='value', ascending=False).reset_index()


g.head(10)

game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000

**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [ ]:
# Write your code here
cond = steam_df['behavior-name'] == 'play'
g = steam_df[cond]
g = g.loc[:, ['game-title', 'value']]
g = g.groupby('game-title')
g = g.mean()
g = g.sort_values(by='value', ascending=False).reset_index()


g.head(10)

**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [72]:
# Write your code here
cond = steam_df['behavior-name'] == 'play'

def sig(x):
    return 1/1 + np.exp(-x/100)

g = steam_df.loc[cond].copy()
g['value'] = g['value'].apply(lambda x: sig(x))

g.head(10)


user-id                  game-title behavior-name     value  zero
1   151603712  The Elder Scrolls V Skyrim          play  1.065219     0
3   151603712                   Fallout 4          play  1.418952     0
5   151603712                       Spore          play  1.861569     0
7   151603712           Fallout New Vegas          play  1.886034     0
9   151603712               Left 4 Dead 2          play  1.914846     0
11  151603712                    HuniePop          play  1.918512     0
13  151603712               Path of Exile          play  1.922194     0
15  151603712                 Poly Bridge          play  1.927743     0
17  151603712                 Left 4 Dead          play  1.967539     0
19  151603712             Team Fortress 2          play  1.972388     0

## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [147]:
# Write your code here
g = ml_df.loc[:].copy()
d = dict()

def f(x):
    stri = str(x).split('|')
    for y in stri:
        if y in d:
            d[y][0]  += 1
        else:
            d[y]  = [1]
            

g['genres'].apply(lambda x: f(x) )


g = g.groupby('genres').count().reset_index()
g = g.loc[:, ['genres', 'userId']]

df_d = {
    'genres': [],
    'n_users': []
}

for key in d:
    df_d['genres'].append(key)
    df_d['n_users'].append(d[key][0])

df = pd.DataFrame.from_dict(df_d)



df = df.sort_values(by='n_users', ascending=False).reset_index()

df = df.loc[:, ['genres', 'n_users']]
display(df)


genres  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47

**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [174]:
# Write your code here
g = ml_df.loc[:].copy()
d = dict()

def f(x, y):
    
    if x in d:
        d[x][0]  += y
        d[x][1] += 1
    else:
        d[x]  = [y, 1]
    
   
            

g.apply(lambda x: f(x.genres, x.rating), axis=1)


g = g.groupby('genres').count().reset_index()
g = g.loc[:, ['genres', 'userId']]

df_d = {
    'genre': [],
    'rating': []
}

for x in d:
    df_d['genre'].append(x)
    df_d['rating'].append(d[x][0]/d[x][1])


df = pd.DataFrame.from_dict(df_d)

df = df.sort_values(by='rating', ascending=False)

display(df)


genre  rating
950         Action|Crime|Drama|Sci-Fi     5.0
844         Comedy|Crime|Drama|Horror     5.0
630        Animation|Children|Mystery     5.0
635             Comedy|Horror|Mystery     5.0
636              Comedy|Crime|Fantasy     5.0
..                                ...     ...
861            Children|Horror|Sci-Fi     0.5
863             Horror|Sci-Fi|Western     0.5
914      Action|Comedy|Horror|Musical     0.5
894  Adventure|Children|Comedy|Sci-Fi     0.5
785     Drama|Fantasy|Sci-Fi|Thriller     0.5

[951 rows x 2 columns]

**Task 17.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print first 10 in the form: title, average rating, bias.

In [217]:
# Write your code here
def deviation(x2, r2, n2):
    return np.sqrt(np.power(np.abs(x2 - r2),2)/n2)
g = ml_df.copy()

g = g.loc[:, ['title', 'rating']]

# g['average rating'] = g.groupby('title').sum()
d = g.groupby('title').mean()

r = g['rating'].mean()
n = len(g.index)

m = pd.merge(g, d, on='title')

m = m.rename({'rating_x': 'bias', 'rating_y': 'average rating'}, axis=1)

m['bias'] = m.apply(lambda x: x['average rating'] - x.bias, axis=1)

m = m.loc[:,['title', 'average rating', 'bias']]


d = d.rename({'rating':'average rating'}, axis=1)
d['bias'] = d.apply(lambda x: deviation(x, r, n))

d.head(10)


average rating      bias
title                                                            
'71 (2014)                                     4.000000  0.001570
'Hellboy': The Seeds of Creation (2004)        4.000000  0.001570
'Round Midnight (1986)                         3.500000  0.000005
'Salem's Lot (2004)                            5.000000  0.004719
'Til There Was You (1997)                      4.000000  0.001570
'Tis the Season for Love (2015)                1.500000  0.006303
'burbs, The (1989)                             3.176471  0.001024
'night Mother (1986)                           3.000000  0.001579
(500) Days of Summer (2009)                    3.666667  0.000520
*batteries not included (1987)                 3.285714  0.000680

**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print first 10 in the form: user_id, average rating, bias.

In [220]:
# Write your code here
# Write your code here
def deviation(x2, r2, n2):
    return np.sqrt(np.power(np.abs(x2 - r2),2)/n2)
g = ml_df.copy()

g = g.loc[:, ['userId', 'rating']]

# g['average rating'] = g.groupby('title').sum()
d = g.groupby('userId').mean()

r = g['rating'].mean()
n = len(g.index)


d = d.rename({'rating':'average rating', 'userId': 'user_id'}, axis=1)
d['bias'] = d.apply(lambda x: deviation(x, r, n))

d.head(10)

average rating      bias
userId                          
1             4.366379  0.002723
2             3.948276  0.001407
3             2.435897  0.003356
4             3.555556  0.000170
5             3.636364  0.000425
6             3.493631  0.000025
7             3.230263  0.000854
8             3.574468  0.000230
9             3.260870  0.000758
10            3.278571  0.000702

**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task.

In [250]:
# Write your code here
g = ml_df.copy()

g1 = g.sample(n=10)
g2 = g.sample(n=10)

display(g1)
display(g2)



userId  movieId  rating   timestamp                            title  \
65855     477     4979     4.5  1200939537     Royal Tenenbaums, The (2001)   
2254      577      316     2.0   945965886                  Stargate (1994)   
67856      63    81229     4.0  1443200311                       Red (2010)   
81462     306   166534     4.0  1518327356                     Split (2017)   
40166     469     2023     3.0   965334279  Godfather: Part III, The (1990)   
87265     571     3018     1.0   966900368               Re-Animator (1985)   
38636     210     8907     1.5  1475611030                Shark Tale (2004)   
76785     135     3098     4.0  1009693996              Natural, The (1984)   
62908     182     2995     1.5  1075859308     House on Haunted Hill (1999)   
54750     483    38061     5.0  1178213543       Kiss Kiss Bang Bang (2005)   

                              genres  
65855                   Comedy|Drama  
2254         Action|Adventure|Sci-Fi  
67856                  Action|Comedy  
81462          Drama|Horror|Thriller  
40166   Crime|Drama|Mystery|Thriller  
87265           Comedy|Horror|Sci-Fi  
38636      Animation|Children|Comedy  
76785                          Drama  
62908                Horror|Thriller  
54750  Comedy|Crime|Mystery|Thriller

userId  movieId  rating   timestamp  \
26278      480      364     3.5  1179162651   
5029       451      661     4.0   854089684   
43205      561    97938     3.0  1491095239   
100311     599    83086     2.5  1498516978   
8964       222     1278     4.0  1391349956   
83472      474     4823     4.0  1002756838   
12598      249     2542     4.0  1346757796   
78567      562     5810     5.0  1368896062   
80037      414    69481     4.5  1273977063   
4497       414      593     4.0   961516659   

                                           title  \
26278                      Lion King, The (1994)   
5029            James and the Giant Peach (1996)   
43205                          Life of Pi (2012)   
100311                          Burlesque (2010)   
8964                   Young Frankenstein (1974)   
83472                         Serendipity (2001)   
12598   Lock, Stock & Two Smoking Barrels (1998)   
78567                              8 Mile (2002)   
80037                    Hurt Locker, The (2008)   
4497            Silence of the Lambs, The (1991)   

                                                 genres  
26278   Adventure|Animation|Children|Drama|Musical|IMAX  
5029       Adventure|Animation|Children|Fantasy|Musical  
43205                              Adventure|Drama|IMAX  
100311                            Drama|Musical|Romance  
8964                                     Comedy|Fantasy  
83472                                    Comedy|Romance  
12598                             Comedy|Crime|Thriller  
78567                                             Drama  
80037                         Action|Drama|Thriller|War  
4497                              Crime|Horror|Thriller

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix for the MovieLens dataset. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here

**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here

**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. To prevent hanging your computer because of RAM shortage use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here